DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
  ID INT NOT NULL,
  NAME VARCHAR(100),
  DEPARTMENT VARCHAR(100),
  CREATED_AT DATE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS MEMBERS CASCADE;

CREATE TABLE MEMBERS (
  KEIYAKU_ID INT NOT NULL,
  MEMBER_ID INT NOT NULL,
  MERCH_ID INT NOT NULL,
  CARD_NUM VARCHAR(100),
  CREATED_AT DATE,
  PRIMARY KEY (KEIYAKU_ID)
);